Laundry/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('LaundryExpert.urls')),
]

LaundryExpert/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



app_name='laundry'
urlpatterns = [
    path('', views.index, name="index"),
    path('index/', views.index, name="index"),
    path('how-it-works/', views.about, name="about"),
    path('help/', views.help, name="help"),
    path('contact/', views.contact, name="contact"),

    path('login/', LoginView.as_view(template_name="login.html"), name="login"),
    path('afterlogin/', views.afterlogin_view, name="afterlogin"),
    path('logout/',auth_views.logout_then_login,name="logout"),

    path('user/sign-up/', views.cregistration, name="cregistration"),
    path('vendor/sign-up/', views.bregistration, name="bregistration"),
    path('delivery-team/sign-up/', views.dregistration, name="dregistration"),

    path('user/home/', views.cdashboard, name="cdashboard"),
    path('user/profile/', views.cprofile, name="cprofile"),
    path('user/home/place-order/', views.shopnames, name="shopnames"),
    path('user/home/orders-status/', views.UserOrderStatus, name="UserOrderStatus"),
    path('ordercompleted', views.ordercompleted, name="ordercompleted"),

    path('bussiness/home/', views.bdashboard, name="bdashboard"),
    path('bussiness/profile/', views.bprofile, name="bprofile"),
    path('bussiness/home/addshop/', views.addshop, name="addshop"),
    path('bussiness/home/orders/', views.requestToPickup, name="requestToPickup"), 
    path('bussiness/home/orders/send-delivery/', views.sendDelivery, name="sendDelivery"),
    path('bussiness/home/orders/send-delivery/choose-agent', views.saveB_COrder, name="saveB_COrder"),

    path('delivery-agent/home/', views.ddashboard, name="ddashboard"),
    path('delivery-agent/profile/', views.dprofile, name="dprofile"),
    path('delivery-agent/home/pickup/', views.deliveryapproval, name="deliveryapproval"),
    path('delivery-agent/home/pickup/accept', views.acceptOrder, name="acceptOrder"),
    path('delivery-agent/home/pickup/decline', views.rejectOrder, name="rejectOrder"),

    path('saveItems/', views.saveItems, name="saveItems"),
    path('customersaveItems/', views.customersaveItems, name="customersaveItems"),
    path('ShopCustomer/', views.ShopCustomer, name="ShopCustomer"),
    path('saveRate/', views.saveRate, name="saveRate"),

   
]

      
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LaundryExpert/forms.py
from django import forms
from .models import CRegistration
from .import models
from django.contrib.auth.models import User

# from .models import CRegistration


# class CRegistrationform(forms.ModelForm):
#     class Meta:
#         model = CRegistration
#         fields = ('cname', 'caddress', 'cemail', 'cphone', 'cpassword')
#         widgets = {
#             'cname': forms.TextInput(attrs={'class': 'form-control'}),
#             'caddress': forms.TextInput(attrs={'class': 'form-control'}),
#             'cemail': forms.TextInput(attrs={'class': 'form-control'}),
#             'cphone': forms.TextInput(attrs={'class': 'form-control'}),
#             'cpassword': forms.TextInput(attrs={'class': 'form-control'}),
#             'password1': forms.TextInput(attrs={'class': 'form-control'}),


#         }


class CustomerUserForm(forms.ModelForm):
    class Meta:
        model=User #django default model
        fields=['first_name','last_name','password','email','username']
        widgets = {
        'password': forms.PasswordInput()
        }
class CustomerForm(forms.ModelForm):
    class Meta:
        model= models.CRegistration
        fields=['address','mobile','profile_pic']


    
class BusinessUserForm(forms.ModelForm):
    class Meta:
        model=User #django default model
        fields=['first_name','password','email','username']
        widgets = {
        'password': forms.PasswordInput()
        }
class BusinessForm(forms.ModelForm):
    class Meta:
        model= models.BRegistration
        fields=['address','mobile','business_pic','lic_no','contactname']

        
       

class DeliveryUserForm(forms.ModelForm):
    class Meta:
        model=User #django default model
        fields=['first_name','password','email','username']
        widgets = {
        'password': forms.PasswordInput()
        }
        
class DeliveryForm(forms.ModelForm):
    class Meta:
        model= models.DRegistration
        fields=['address','mobile','delivery_pic','lic_pic','lic_no']

class BDetailsForm(forms.ModelForm):
    class Meta:
        model=models.BDetails
        fields=['first_name','rate1','rate2','rate3','rate4','rate5','rate6','services1','services2','services3','services4','services5','services6']

LaundryExpert/views.py
from django.shortcuts import redirect,render
from .forms import *            # add  * so everything will be added automatically
from .models import *       
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404
from django.urls import reverse,resolve
# from .models import registration
 # Create your views here.
from django.core.mail import send_mail

                # STATIC PAGES
def index(request):
    return render(request,'index.html')

def about(request):
    return render(request,'about.html')
def help(request):
    return render(request,'help.html')
def contact(request):
    return render(request,'contact.html')



                #REGISTRATIONS...

def cregistration(request): 
    form= CustomerUserForm()
    userForm1= CustomerForm()
    mydict={'form':form,'userForm1':userForm1}
    if request.method=='POST':
        form= CustomerUserForm(request.POST)
        userForm1= CustomerForm(request.POST, request.FILES)#profile pic
        if form.is_valid() and userForm1.is_valid():
            print(1)
            user=form.save()
            user.set_password(user.password)
            user.save()
            messages.success(request, 'Your account has been created! Please log in to continue...')
            print(user)
            Customer=userForm1.save(commit=True) #VARIABLE
            Customer.user=user
            Customer.save()
            print(Customer)
            group = Group.objects.get_or_create(name='Customers')#group name
            group[0].user_set.add(user)
            return redirect('laundry:login')
        messages.success(request, 'It is a mistake on our end. Please try again!!')

    return render(request,'cregistration.html',context=mydict)

def bregistration(request):
   
    form= BusinessUserForm()
    buserForm1= BusinessForm()
    mydict={'form':form,'buserForm1':buserForm1}
    if request.method=='POST':
        
        form= BusinessUserForm(request.POST)
        buserForm1= BusinessForm(request.POST, request.FILES) #profile pic
        if form.is_valid() and buserForm1.is_valid():           
            print(1)
            user=form.save()
            # send send_mail
            email=user.email
            print('email is',email)
            subject = 'Subject of the email'
            message = 'Message of the email'
            from_email = 'laundrydazzle@example.com'
            recipient_list = [email]
            send_mail(subject, message, from_email, recipient_list)
            # send send_mail

            user.set_password(user.password)
            user.save()
            messages.success(request, 'Your account has been created! Please log in to continue...')
            print(user)
            BRegistration=buserForm1.save(commit=True) #VARIABLE
            BRegistration.user=user
            BRegistration.save()
            print(BRegistration)
            group = Group.objects.get_or_create(name='Business') #group name
            group[0].user_set.add(user)

            return redirect('laundry:login')
        messages.success(request, 'It is a mistake on our end. Please try again!!')


    return render(request,'bregistration.html',context=mydict)

def dregistration(request):
    form= DeliveryUserForm()
    duserForm1= DeliveryForm()
    mydict={'form':form,'duserForm1':duserForm1}
    if request.method=='POST':
        form= DeliveryUserForm(request.POST)
        duserForm1= DeliveryForm(request.POST, request.FILES) #profile pic
        if form.is_valid() and duserForm1.is_valid():
            print(1)
            user=form.save()
            user.set_password(user.password)
            user.save()
            messages.success(request, 'Your registration has been completed! Please wait for verification from the administrator. Then you will be able to log in')
            print(user)
            DRegistration=duserForm1.save(commit=True) #VARIABLE
            DRegistration.user=user
            DRegistration.save()
            print(DRegistration)
            group = Group.objects.get_or_create(name='Delivery') #group name
            group[0].user_set.add(user)
            return redirect('laundry:index')
        messages.success(request, 'It is a mistake on our end. Please try again!!')

    return render(request,'dregistration.html',context=mydict)

def addshop(request):
    var1=BRegistration.objects.get(user_id=request.user)
    cr=var1.user.first_name
    print(cr)
  
    form2=BDetailsForm(instance=var1.user)
    mydict={
       'var1':var1,
       'cr':cr,
        'form2':form2,
    }
    if request.method=='POST':
        # var1=BRegistration.objects.get(user_id=request.user)
        
        form2=BDetailsForm(request.POST)
        if form2.is_valid():
            user1=form2.save()
            user1.user=request.user
            user1.save()
            return redirect('laundry:bdashboard')
        else :
            print("Invalid Form")
    return render(request,'addshop.html',context=mydict)


                #GROUPS...

def Customer(user):
    print(user)
    return user.groups.filter(name='Customers').exists()

def Business(user):
    print(user.groups.filter(name='Business').exists())
    return user.groups.filter(name='Business').exists()

def Delivery(user):
    print("Delivery")
    return user.groups.filter(name='Delivery').exists()


                #LOGOUT

# @login_required
# def logout_user(request):
#     logout(request)
#     return redirect('/login')

                #LOGIN REQUIRED PAGES

@login_required(login_url='login')
@user_passes_test(Customer)
def cdashboard(request):
    return render(request,'cdashboard.html')

@login_required(login_url='laundry:login')
@user_passes_test(Customer)
def cprofile(request):    
    cust =CRegistration.objects.get(user_id=request.user.id)
    #my_volunteer1 = Doctor.objects.filter(my_volunteer.gender)
    # c=far.mobile
    if request.method == "POST":
        cust =CRegistration.objects.get(user_id=request.user)
        form = CustomerUserForm(request.POST, instance=cust.user)

        userForm1 = CustomerForm(request.POST, instance=cust)
        if form.is_valid() and userForm1.is_valid():
            user=form.save()
            if(user.password!=""):
                user.set_password(user.password)            
            user.save()
            print(form)
            userForm1.save()
            messages.success(request, 'Your Account has been Updated')
            # return redirect('cdashboard')
            url = reverse('laundry:login')
            return redirect(url)
    else:
            form = CustomerUserForm(instance=cust.user)
            userForm1 = CustomerForm(instance=cust)
            context = {

            'form': form,
            'userForm1': userForm1,
            # 'c':c
            }
    return render(request, 'cprofile.html', context)


@login_required(login_url='laundry:login')
@user_passes_test(Business)
def bdashboard(request):
    return render(request,'bdashboard.html')
    # return redirect('laundry:bdashboard')

@login_required(login_url='laundry:login')
@user_passes_test(Business)
def bprofile(request):    
    bus =BRegistration.objects.get(user_id=request.user.id)
    #my_volunteer1 = Doctor.objects.filter(my_volunteer.gender)
    # c=far.mobile
    if request.method == "POST":
        bus =BRegistration.objects.get(user_id=request.user)
        form = BusinessUserForm(request.POST, instance=bus.user)

        buserForm1 = BusinessForm(request.POST, instance=bus)
        if form.is_valid() and buserForm1.is_valid():
            user=form.save()
            user.set_password(user.password)
            user.save()
            print(form)
            buserForm1.save()
            messages.success(request, 'Your Account has been Updated')
            url = reverse('laundry:login')
            return redirect(url)
    else:
            form = BusinessUserForm(instance=bus.user)
            buserForm1 = BusinessForm(instance=bus)
            context = {

            'form': form,
            'buserForm1': buserForm1,
            # 'c':c
            }
    return render(request, 'bprofile.html', context)



@login_required(login_url='login')
@user_passes_test(Delivery)
def ddashboard(request):
    return render(request,'ddashboard.html')

@login_required(login_url='login')
@user_passes_test(Delivery)
def dprofile(request):    
    deliv =DRegistration.objects.get(user_id=request.user.id)
    #my_volunteer1 = Doctor.objects.filter(my_volunteer.gender)
    # c=far.mobile
    if request.method == "POST":
        deliv =DRegistration.objects.get(user_id=request.user)
        form = DeliveryUserForm(request.POST, instance=deliv.user)

        duserForm1 = DeliveryForm(request.POST, instance=deliv)
        if form.is_valid() and duserForm1.is_valid():
            user=form.save()
            user.set_password(user.password)
            user.save()
            print(form)
            duserForm1.save()
            messages.success(request, 'Your Account has been Updated')
            url = reverse('laundry:login')
            return redirect(url)
    else:
            form = DeliveryUserForm(instance=deliv.user)
            duserForm1 = DeliveryForm(instance=deliv)
            context = {

            'form': form,
            'duserForm1': duserForm1,
            # 'c':c
            }
    return render(request, 'dprofile.html', context)


                #AFTER LOGIN FUNCTIONS
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
 
def afterlogin_view(request):
    if Customer(request.user):   
        print('username',request.user)
        print('username type',type(request.user))
        u=str(request.user)
        request.session['user']=u
        request.session['userid']=request.user.id
        # print('u')

LaundryExpert/templates/deliveryapproval.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>DevFolio - Developer Portfolio Template</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Free Website Template" name="keywords">
        <meta content="Free Website Template" name="description">

        <!-- Favicon -->
        <link href="{% static 'd.dash_assets/img/favicon.ico' %}" rel="icon">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'd.dash_assets/lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'd.dash_assets/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'd.dash_assets/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'd.dash_assets/css/style.css' %}" rel="stylesheet">
    </head>

    <body data-spy="scroll" data-target=".navbar" data-offset="51">
        <!-- Nav Bar Start -->
        <div class="navbar navbar-expand-lg bg-light navbar-light">
            <div class="container-fluid">
                <a href="index.html" class="navbar-brand">DevFolio</a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto">
                        <a href="{% url 'laundry:ddashboard' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'laundry:dprofile' %}" class="nav-item nav-link active" >Profile</a>
                        <a href="{% url 'laundry:deliveryapproval' %}" class="nav-item nav-link active">PickUp</a>
                        <a href="{% url 'laundry:logout' %}" class="nav-item nav-link active">Logout</a>
                       
                    </div>
                </div>
            </div>
        </div>
        <!-- Nav Bar End -->


        


        <!-- Team Start -->
        <div class="team" id="team">
            <div class="container">
                <div class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
                    <p>My Pickup list</p>
                    <h2>Accept/Decliine your order</h2>
                </div>
                <div class="row">
                    {% for al in data %}
                    <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.0s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static 'd.dash_assets/img/team-1.jpg' %}" alt="Image">
                            </div>
                            
                            <div class="team-text">
                                <h2>{{al.userC.username}}</h2>
                                <h4>{{al.clothingItems}}</h4>
                                <h4>Phone : {{al.ph}}</h4>
                                <h4>Address : {{al.address}}</h4>
                                
                                <div class="hero-btn">
                                    <a class="btn" style="color: azure" href="{% url 'laundry:acceptOrder' %}?id={{al.id}}">Accept</a><br><br>
                                    <a class="btn" style="color: azure" href="{% url 'laundry:rejectOrder' %}?id={{al.id}}">Decline</a><br><br>
                                    <!-- <a class="btn" href=""><i class="fab fa-facebook-f"></i></a> -->
                                    <!-- <a class="btn" href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a class="btn" href=""><i class="fab fa-instagram"></i></a> -->
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                <h5>You have no pending orders</h5>
                    {% endfor %}
                    <!-- <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.2s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static 'd.dash_assets/img/team-2.jpg' %}" alt="Image">
                            </div>
                            <div class="team-text">
                                <h2>Dylan Adams</h2>
                                <h4>Web Developer</h4>
                                <p>
                                    Lorem ipsum dolor sit amet consec adipis elit. Etiam accum lacus
                                </p>
                                <div class="team-social">
                                    <a class="btn" href=""><i class="fab fa-twitter"></i></a>
                                    <a class="btn" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn" href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a class="btn" href=""><i class="fab fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div> 
                    <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.4s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static 'd.dash_assets/img/team-3.jpg' %}" alt="Image">
                            </div>
                            <div class="team-text">
                                <h2>Jennifer Page</h2>
                                <h4>Apps Designer</h4>
                                <p>
                                    Lorem ipsum dolor sit amet consec adipis elit. Etiam accum lacus
                                </p>
                                <div class="team-social">
                                    <a class="btn" href=""><i class="fab fa-twitter"></i></a>
                                    <a class="btn" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn" href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a class="btn" href=""><i class="fab fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.6s">
                        <div class="team-item">
                            <div class="team-img">
                                <img src="{% static 'd.dash_assets/img/team-4.jpg' %}" alt="Image">
                            </div>
                            <div class="team-text">
                                <h2>Josh Dunn</h2>
                                <h4>Apps Developer</h4>
                                <p>
                                    Lorem ipsum dolor sit amet consec adipis elit. Etiam accum lacus
                                </p>
                                <div class="team-social">
                                    <a class="btn" href=""><i class="fab fa-twitter"></i></a>
                                    <a class="btn" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn" href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a class="btn" href=""><i class="fab fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>-->
                </div>
            </div>
        </div>
        <!-- Team End -->
        
        


        <!-- Footer Start -->
        <div class="footer wow fadeIn" data-wow-delay="0.3s">
            <div class="container-fluid">
                <div class="container">
                    <div class="footer-info">
                        <h2>Kate Winslet</h2>
                        <h3>123 Street, New York, USA</h3>
                        <div class="footer-menu">
                            <p>+012 345 67890</p>
                            <p>info@example.com</p>
                        </div>
                        <div class="footer-social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
                <div class="container copyright">
                    <p>&copy; <a href="#">Your Site Name</a>, All Right Reserved | Designed By <a href="https://htmlcodex.com">HTML Codex</a></p>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        
        
        <!-- Back to top button -->
        <a href="#" class="btn back-to-top"><i class="fa fa-chevron-up"></i></a>
        
        
        <!-- Pre Loader -->
        <div id="loader" class="show">
            <div class="loader"></div>
        </div>

        
        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'd.dash_assets/lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'd.dash_assets/lib/wow/wow.min.js' %}"></script>
        <script src="{% static 'd.dash_assets/lib/waypoints/waypoints.min.js' %}"></script>
        <script src="{% static 'd.dash_assets/lib/typed/typed.min.js' %}"></script>
        <script src="{% static 'd.dash_assets/lib/owlcarousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'd.dash_assets/lib/isotope/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'd.dash_assets/lib/lightbox/js/lightbox.min.js' %}"></script>
        
        <!-- Contact Javascript File -->
        <script src="{% static 'd.dash_assets/mail/jqBootstrapValidation.min.js' %}"></script>
        <script src="{% static 'd.dash_assets/mail/contact.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'd.dash_assets/js/main.js' %}"></script>
    </body>
</html>

LaundryExpert/templates/dprofile.html
{% load static %}
<!DOCTYPE html>
<html>
{% load widget_tweaks %}

<head>
	<meta charset="utf-8">
	<title>Form-v9 by Colorlib</title>
	<!-- called the below css file from index_assets only to display -class="alert alert-warning"-   -->
	<link href="{% static 'index_assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	<!-- Mobile Specific Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- Font-->
	<link rel="stylesheet" type="text/css" href="{% static 'd.reg_assets/css/nunito-font.css' %}">
	<!-- Main Style Css -->
    <link rel="stylesheet" href="{% static 'd.reg_assets/css/style.css' %}"/>
</head>
<body class="form-v9">
	<div class="page-content">
		<div class="form-v9-content" style="background-image: url('/static/d.reg_assets/images/form-v9.jpg')">
			{% if messages %}
				<div class="alert alert-warning" role="alert">
				  There was a mistake on our part. We apologize for the inconvenience.<br> Please <a href="{{ request.get_full_path }}" class="alert-link">Try again</a>
				</div>
			{% endif %}			
<!-- {% if messages %}
	<ul class="form-detail">
		{% for message in messages %}
			<div {% if message.tags %} class="form-v9" {% endif %}><p> {{ message }} </p>
			<a class="" href="{{ request.get_full_path }}"><b style="color: rgba(255, 255, 255, 0.856) ">Retry</b></a></div>
		{% endfor %}
	</ul>
{% endif %} -->
			<form class="form-detail" method="post">
				{% csrf_token %}
				<h2>Registration Form</h2>
				<div class="form-row-total">
					<div class="form-row">
						<!-- <input type="text" name="full-name" id="full-name" class="input-text" placeholder="Your Name" required> -->
						{% render_field form.first_name class="input-text" placeholder=" enter your name" %}
					</div>
					<div class="form-row">
						<!-- <input type="text" name="your-email" id="your-email" class="input-text" placeholder="Your Phone"> -->
						{% render_field duserForm1.mobile pattern="[0-9]{10}" class="input-text" placeholder="Please enteryour 10 digit phone number" %}
					</div>
				</div>
				<div class="form-row-total">
					<div class="form-row">
						<!-- <input type="text" name="your-email" id="your-email" class="input-text" placeholder="Your Email" required pattern="[^@]+@[^@]+.[a-zA-Z]{2,6}" -->
						{% render_field form.email class="input-text" placeholder="example@example.com" %}
					</div>
					<div class="form-row">
						<!-- <input type="password" name="comfirm-password" id="comfirm-password" class="input-text" placeholder="username" required> -->
						{% render_field form.username class="input-text" placeholder="Create a unique username" %}
					</div>
				</div>

				<div class="form-row-total">
					<div class="form-row">
						<!-- <input type="text" name="your-email" id="your-email" class="input-text" placeholder="Your address" required pattern="[^@]+@[^@]+.[a-zA-Z]{2,6}"> -->
						{% render_field duserForm1.address class="input-text" placeholder="Please enter your address" %}
					</div>
					<div class="form-row">
						<!-- <input type="password" name="comfirm-password" id="comfirm-password" class="input-text" placeholder="profile pic" required> -->
						{% render_field duserForm1.delivery_pic class="input-text" placeholder="Choose a profile Picture" %}
					</div>
				</div>


				<div class="form-row-total">
					<div class="form-row">
						<!-- <input type="text" name="your-email" id="your-email" class="input-text" placeholder="Your address" required pattern="[^@]+@[^@]+.[a-zA-Z]{2,6}"> -->
						{% render_field duserForm1.lic_no class="input-text" placeholder="Enter your Licence number" %}
					</div>
					<div class="form-row">
						<!-- <input type="password" name="comfirm-password" id="comfirm-password" class="input-text" placeholder="profile pic" required> -->
						{% render_field duserForm1.lic_pic class="input-text" placeholder="Choose a profile Picture" %}
					</div>
					
				</div>
			{% render_field form.password class="input-text" placeholder="Password must include upper and lower case letters,symbols and numbers" %}
				
				<div class="form-row-last">
					<input type="submit" name="register" class="register" value="Register">
				</div>
			</form>

		</div>
	</div>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>